<?php

namespace Database\Seeders;

use App\Models\Problem;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProblemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Problem::create([
            'pstyle'=>'1',
            'answer_text'=>'北海道地域の旧称としてもっとも相応しいものを一つ選べ。',
            'pre_answer'=>'信濃#博多#加賀#蝦夷地',
            'correct_answer'=>'蝦夷地',
            'province_num'=>'6',
            'ganre_num'=>'2',
            'level_num'=>'1',
            'problem_time'=>'20',
        ]);

        Problem::create([
            'pstyle'=>'1',
            'answer_text'=>'北海道の先住民族としてもっとも相応しいものを一つ選べ。',
            'pre_answer'=>'マサイ族#アイヌ民族#アボリジニ#バスク民族',
            'correct_answer'=>'アイヌ民族',
            'province_num'=>'6',
            'ganre_num'=>'2',
            'level_num'=>'1',
            'problem_time'=>'20',
        ]);
        Problem::create([
            'pstyle'=>'1',
            'answer_text'=>'北海道にある政令指定都市を全て選べ。',
            'pre_answer'=>'釧路市#旭川市#帯広市#札幌市',
            'correct_answer'=>'札幌市',
            'province_num'=>'6',
            'ganre_num'=>'2',
            'level_num'=>'1',
            'problem_time'=>'20',
        ]);
        Problem::create([
            'pstyle'=>'3',
            'pre_answer' => '',
            'answer_text'=>'日本で最北端の刑務所はどこか？',
            'correct_answer'=>'網走刑務所',
            'province_num'=>'6',
            'ganre_num'=>'2',
            'level_num'=>'1',
            'problem_time'=>'20',
        ]);
        Problem::create([
            'pstyle'=>'3',
            'pre_answer' => '',
            'answer_text'=>'日米和親条約(1854年)の締結により開港することになったのは下田ともう一つはどこか？',
            'correct_answer'=>'箱館#函館',
            'province_num'=>'6',
            'ganre_num'=>'2',
            'level_num'=>'1',
            'problem_time'=>'20',
        ]);
        Problem::create([
            'pstyle'=>'1',
            'answer_text'=>'東京の旧称としてもっとも相応しいものを下記から一つ選べ。',
            'pre_answer'=>'近江#尾張#越後#江戸',
            'correct_answer'=>'江戸',
            'province_num'=>'7',
            'ganre_num'=>'2',
            'level_num'=>'1',
            'problem_time'=>'20',
        ]);
        Problem::create([
            'pstyle'=>'3',
            'pre_answer' => '',
            'answer_text'=>'東京都内を流れる川の中で最も長いものは何か？',
            'correct_answer'=>'利根川',
            'province_num'=>'7',
            'ganre_num'=>'2',
            'level_num'=>'1',
            'problem_time'=>'20',
        ]);
        Problem::create([
            'pstyle'=>'2',
            'answer_text'=>'下記の中で東京都内に含まれる島名を全て選べ。',
            'pre_answer'=>'三宅島#奄美大島#伊豆大島#佐渡島',
            'correct_answer'=>'三宅島と#伊豆大島',
            'province_num'=>'7',
            'ganre_num'=>'2',
            'level_num'=>'1',
            'problem_time'=>'20',
        ]);
        Problem::create([
            'pstyle'=>'3',
            'pre_answer' => '',
            'answer_text'=>'次の□にあてはまる最もふさわしい語を書いて下さい。
            「東京都の築地市場は2018年にその機能を□市場に移転した。」',
            'correct_answer'=>'豊洲',
            'province_num'=>'7',
            'ganre_num'=>'2',
            'level_num'=>'1',
            'problem_time'=>'20',
        ]);
        Problem::create([
            'pstyle'=>'3',
            'pre_answer' => '',
            'answer_text'=>'1603年に江戸幕府を開いた人物は誰か。',
            'correct_answer'=>'徳川家康',
            'province_num'=>'7',
            'ganre_num'=>'2',
            'level_num'=>'1',
            'problem_time'=>'20',
        ]);
        Problem::create([
            'pstyle'=>'3',
            'pre_answer' => '',
            'answer_text'=>'次の□にあてはまる語を書いて下さい。
            「1854年にペリーらと幕府が日米和親条約に関して会談を行ったのは現在の神奈川県□市である。」',
            'correct_answer'=>'横浜',
            'province_num'=>'8',
            'ganre_num'=>'2',
            'level_num'=>'1',
            'problem_time'=>'20',
        ]);
        Problem::create([
            'pstyle'=>'3',
            'pre_answer' => '',
            'answer_text'=>'大森頼春や北条早雲が城主であった神奈川県にある城は何か。',
            'correct_answer'=>'小田原城',
            'province_num'=>'8',
            'ganre_num'=>'2',
            'level_num'=>'1',
            'problem_time'=>'20',
        ]);
        Problem::create([
            'pstyle'=>'1',
            'answer_text'=>'12世紀末に征夷大将軍となり、鎌倉に幕府を開いた人物は誰か。次の中からもっとも適切なものを選べ。',
            'pre_answer'=>'徳川家康#豊臣秀吉#源頼朝#足利尊氏',
            'correct_answer'=>'源頼朝',
            'province_num'=>'8',
            'ganre_num'=>'2',
            'level_num'=>'1',
            'problem_time'=>'20',
        ]);
        Problem::create([
            'pstyle'=>'3',
            'pre_answer' => '',
            'answer_text'=>'湖畔に明治2年（1869年）まであった、江戸幕府によって設置されていた東海道の関所は何か。',
            'correct_answer'=>'箱根関所#箱根関',
            'province_num'=>'8',
            'ganre_num'=>'2',
            'level_num'=>'1',
            'problem_time'=>'20',
        ]);
        Problem::create([
            'pstyle'=>'3',
            'pre_answer' => '',
            'answer_text'=>'横須賀市、鎌倉市、逗子市、三浦市、葉山町周辺の半島の名称は何か。',
            'correct_answer'=>'三浦半島',
            'province_num'=>'8',
            'ganre_num'=>'2',
            'level_num'=>'1',
            'problem_time'=>'20',
        ]);
        Problem::create([
            'pstyle'=>'1',
            'answer_text'=>'沖縄県地方の別称は何か。次の中からもっとも相応しいものを一つ選べ。',
            'pre_answer'=>'薩摩#土佐#飛騨#琉球',
            'correct_answer'=>'琉球',
            'province_num'=>'9',
            'ganre_num'=>'2',
            'level_num'=>'1',
            'problem_time'=>'20',
        ]);
        Problem::create([
            'pstyle'=>'2',
            'answer_text'=>'次の中で沖縄県に属する島名を全て選べ。',
            'pre_answer'=>'竹富島#与那国島#八丈島#波照間島',
            'correct_answer'=>'竹富島、B.与那国島、D.波照間島',
            'province_num'=>'9',
            'ganre_num'=>'2',
            'level_num'=>'1',
            'problem_time'=>'20',
        ]);
        Problem::create([
            'pstyle'=>'2',
            'answer_text'=>'1429年から琉球王国の首都となったのはどこか。次の中からもっとも適しているものを選べ。',
            'pre_answer'=>'首里#北京#巴里#名護',
            'correct_answer'=>'首里',
            'province_num'=>'9',
            'ganre_num'=>'2',
            'level_num'=>'1',
            'problem_time'=>'20',
        ]);
        Problem::create([
            'pstyle'=>'3',
            'pre_answer' => '',
            'answer_text'=>'琉球は1609年にどこからの侵攻を受けたか。藩の名称を答えよ。',
            'correct_answer'=>'薩摩藩',
            'province_num'=>'9',
            'ganre_num'=>'2',
            'level_num'=>'1',
            'problem_time'=>'20',
        ]);
        Problem::create([
            'pstyle'=>'1',
            'answer_text'=>'沖縄の食文化において医食同源の理念に沿った「食は薬」を意味する言葉は何か。次の中からもっとも相応しいものを一つ選べ。',
            'pre_answer'=>'チャンプルー#チンスコウ#クスイムン#グンボーマチ',
            'correct_answer'=>'クスイムン',
            'province_num'=>'9',
            'ganre_num'=>'2',
            'level_num'=>'1',
            'problem_time'=>'20',
        ]);
        Problem::create([
            'pstyle'=>'1',
            'pre_answer'=>'',
            'answer_text'=>'長野県長野市にある無宗派の寺で、運営が天台宗と浄土宗の両宗派によって行われており、本尊が絶対秘仏とされている寺はどこか。',
            'correct_answer'=>'善光寺(信濃善光寺も可)',
            'province_num'=>'9',
            'ganre_num'=>'2',
            'level_num'=>'1',
            'problem_time'=>'20',
        ]);
        Problem::create([
            'pstyle'=>'1',
            'answer_text'=>'戦国時代に武田信玄と上杉謙信による戦いのことを何というか。次の中からもっとも相応しいものを一つ選べ。',
            'pre_answer'=>'関ヶ原の戦い#長篠の戦い#川中島の戦い#戊辰戦争',
            'correct_answer'=>'川中島の戦い',
            'province_num'=>'9',
            'ganre_num'=>'2',
            'level_num'=>'1',
            'problem_time'=>'20',
        ]);
        Problem::create([
            'pstyle'=>'3',
            'pre_answer' => '',
            'answer_text'=>'日本で最も標高が高い市はどこか。市役所の位置で比較したものとする。',
            'correct_answer'=>'茅野市',
            'province_num'=>'9',
            'ganre_num'=>'2',
            'level_num'=>'1',
            'problem_time'=>'20',
        ]);
        Problem::create([
            'pstyle'=>'1',
            'answer_text'=>'木曽駒ヶ岳や空木岳を含む、中央アルプスとも言われる山脈を何というか。',
            'pre_answer'=>'日高山脈#木曽山脈#奥羽山脈#飛騨山脈',
            'correct_answer'=>'木曽山脈',
            'province_num'=>'9',
            'ganre_num'=>'2',
            'level_num'=>'1',
            'problem_time'=>'20',
        ]);
        Problem::create([
            'pstyle'=>'3',
            'pre_answer' => '',
            'answer_text'=>'真田昌幸によって築城され,真田氏・仙石氏・松平氏が城主となった城は何か。',
            'correct_answer'=>'上田城#尼ヶ淵城',
            'province_num'=>'4',
            'ganre_num'=>'2',
            'level_num'=>'1',
            'problem_time'=>'20',
        ]);
    }
}



