<?php

namespace Database\Seeders;

use App\Models\Province;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProvinceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        Province::create([
            'region_name'=>'関東地方',
            'name'=>'東京',
            'img_url'=>asset('img/top/test_area/top_tokyo.jpg')
        ]);
        Province::create([
            'region_name'=>'関東地方',
            'name'=>'茨城',
            'img_url'=>asset('img/top/test_area/blank_city.png')
        ]);
        Province::create([
            'region_name'=>'関東地方',
            'name'=>'栃木',
            'img_url'=>asset('img/top/test_area/blank_city.png')
        ]);
        Province::create([
            'region_name'=>'関東地方',
            'name'=>'群馬',
            'img_url'=>asset('img/top/test_area/blank_city.png')
        ]);
        Province::create([
            'region_name'=>'関東地方',
            'name'=>'埼玉',
            'img_url'=>asset('img/top/test_area/blank_city.png')
        ]);
        Province::create([
            'region_name'=>'関東地方',
            'name'=>'千葉',
            'img_url'=>asset('img/top/test_area/blank_city.png')
        ]);
        Province::create([
            'region_name'=>'関東地方',
            'name'=>'神奈川',
            'img_url'=>asset('img/top/test_area/top_kanagawa.jpg')
        ]);
        
        Province::create([
            'region_name'=>'東北地方',
            'name'=>'青森',
            'img_url'=>asset('img/top/test_area/blank_city.png')
        ]);
        Province::create([
            'region_name'=>'東北地方',
            'name'=>'岩手',
            'img_url'=>asset('img/top/test_area/blank_city.png')
        ]);
        Province::create([
            'region_name'=>'東北地方',
            'name'=>'宮城',
            'img_url'=>asset('img/top/test_area/blank_city.png')
        ]);
        Province::create([
            'region_name'=>'東北地方',
            'name'=>'秋田',
            'img_url'=>asset('img/top/test_area/blank_city.png')
        ]);
        Province::create([
            'region_name'=>'東北地方',
            'name'=>'山形',
            'img_url'=>asset('img/top/test_area/blank_city.png')
        ]);
        Province::create([
            'region_name'=>'東北地方',
            'name'=>'福島',
            'img_url'=>asset('img/top/test_area/blank_city.png')
        ]);
        
        Province::create([
            'region_name'=>'中部地方',
            'name'=>'新潟',
            'img_url'=>asset('img/top/test_area/blank_city.png')
        ]);
        Province::create([
            'region_name'=>'中部地方',
            'name'=>'富山',
            'img_url'=>asset('img/top/test_area/blank_city.png')
        ]);
        Province::create([
            'region_name'=>'中部地方',
            'name'=>'石川',
            'img_url'=>asset('img/top/test_area/blank_city.png')
        ]);
        Province::create([
            'region_name'=>'中部地方',
            'name'=>'福井',
            'img_url'=>asset('img/top/test_area/blank_city.png')
        ]);
        Province::create([
            'region_name'=>'中部地方',
            'name'=>'山梨',
            'img_url'=>asset('img/top/test_area/blank_city.png')
        ]);
        Province::create([
            'region_name'=>'中部地方',
            'name'=>'長野',
            'img_url'=>asset('img/top/test_area/top_nagano.png')
        ]);
        Province::create([
            'region_name'=>'中部地方',
            'name'=>'岐阜',
            'img_url'=>asset('img/top/test_area/blank_city.png')
        ]);
        Province::create([
            'region_name'=>'中部地方',
            'name'=>'静岡',
            'img_url'=>asset('img/top/test_area/blank_city.png')
        ]);
        Province::create([
            'region_name'=>'中部地方',
            'name'=>'愛知',
            'img_url'=>asset('img/top/test_area/blank_city.png')
        ]);
        
        
        Province::create([
            'region_name'=>'九州・沖縄地方',
            'name'=>'福岡',
            'img_url'=>asset('img/top/test_area/top_fukuoka.png')
        ]);
        Province::create([
            'region_name'=>'九州・沖縄地方',
            'name'=>'佐賀',
            'img_url'=>asset('img/top/test_area/blank_city.png')
        ]);
        Province::create([
            'region_name'=>'九州・沖縄地方',
            'name'=>'長崎',
            'img_url'=>asset('img/top/test_area/blank_city.png')
        ]);
        Province::create([
            'region_name'=>'九州・沖縄地方',
            'name'=>'熊本',
            'img_url'=>asset('img/top/test_area/blank_city.png')
        ]);
        Province::create([
            'region_name'=>'九州・沖縄地方',
            'name'=>'大分',
            'img_url'=>asset('img/top/test_area/blank_city.png')
        ]);
        Province::create([
            'region_name'=>'九州・沖縄地方',
            'name'=>'宮崎',
            'img_url'=>asset('img/top/test_area/blank_city.png')
        ]);
        Province::create([
            'region_name'=>'九州・沖縄地方',
            'name'=>'鹿児島',
            'img_url'=>asset('img/top/test_area/blank_city.png')
        ]);
        Province::create([
            'region_name'=>'九州・沖縄地方',
            'name'=>'沖縄',
            'img_url'=>asset('img/top/test_area/top_okinawa.jpg')
        ]);
        
        Province::create([
            'region_name'=>'四国地方',
            'name'=>'徳島',
            'img_url'=>asset('img/top/test_area/blank_city.png')
        ]);
        Province::create([
            'region_name'=>'四国地方',
            'name'=>'香川',
            'img_url'=>asset('img/top/test_area/top_kagawa.png')
        ]);
        Province::create([
            'region_name'=>'四国地方',
            'name'=>'愛媛',
            'img_url'=>asset('img/top/test_area/blank_city.png')
        ]);
        Province::create([
            'region_name'=>'四国地方',
            'name'=>'高知',
            'img_url'=>asset('img/top/test_area/blank_city.png')
        ]);
        
        
        Province::create([
            'region_name'=>'中国地方',
            'name'=>'鳥取',
            'img_url'=>asset('img/top/test_area/blank_city.png')
        ]);
        Province::create([
            'region_name'=>'中国地方',
            'name'=>'島根',
            'img_url'=>asset('img/top/test_area/blank_city.png')
        ]);
        Province::create([
            'region_name'=>'中国地方',
            'name'=>'岡山',
            'img_url'=>asset('img/top/test_area/blank_city.png')
        ]);
        Province::create([
            'region_name'=>'中国地方',
            'name'=>'広島',
            'img_url'=>asset('img/top/test_area/top_hiroshima.png')
        ]);
        Province::create([
            'region_name'=>'中国地方',
            'name'=>'山口',
            'img_url'=>asset('img/top/test_area/blank_city.png')
        ]);
        
        Province::create([
            'region_name'=>'近畿地方',
            'name'=>'三重',
            'img_url'=>asset('img/top/test_area/blank_city.png')
        ]);
        Province::create([
            'region_name'=>'近畿地方',
            'name'=>'滋賀',
            'img_url'=>asset('img/top/test_area/blank_city.png')
        ]);
        Province::create([
            'region_name'=>'近畿地方',
            'name'=>'京都',
            'img_url'=>asset('img/top/test_area/blank_city.png')
        ]);
        Province::create([
            'region_name'=>'近畿地方',
            'name'=>'大阪',
            'img_url'=>asset('img/top/test_area/top_akita.png')
        ]);
        Province::create([
            'region_name'=>'近畿地方',
            'name'=>'兵庫',
            'img_url'=>asset('img/top/test_area/blank_city.png')
        ]);
        Province::create([
            'region_name'=>'近畿地方',
            'name'=>'奈良',
            'img_url'=>asset('img/top/test_area/blank_city.png')
        ]);
        Province::create([
            'region_name'=>'近畿地方',
            'name'=>'和歌山',
            'img_url'=>asset('img/top/test_area/blank_city.png')
        ]);
        
        Province::create([
            'region_name'=>'北海道地方',
            'name'=>'北海',
            'img_url'=>asset('img/top/test_area/top_hokaido.jpg')
        ]);
    }
}
