<?php

namespace Database\Seeders;

use App\Models\Test;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class TestSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Test::create([
            'name'=>'aaa',
            'test_date'=> Carbon::parse('2023-07-02'),
            'begin_time'=>'18:40:00',
            'end_time'=>'19:00:00',
            'ganre_id'=>'2',
            'level_id'=>'1',
            'province_id'=>'1',
            'price'=>'4500'
        ]);
        Test::create([
            'name'=>'bbb',
            'test_date'=>Carbon::parse('2023-07-19'),
            'begin_time'=>'15:00:00',
            'end_time'=>'16:00:00',
            'ganre_id'=>'3',
            'level_id'=>'2',
            'province_id'=>'2',
            'price'=>'3000'
        ]);
        Test::create([
            'name'=>'ccc',
            'test_date'=>Carbon::parse('2024-07-13'),
            'begin_time'=>'19:00:00',
            'end_time'=>'20:00:00',
            'ganre_id'=>'2',
            'level_id'=>'1',
            'province_id'=>'3',
            'price'=>'1000'
        ]);
        Test::create([
            'name'=>'ddd',
            'test_date'=>Carbon::parse('2023-07-21'),
            'begin_time'=>'17:00:00',
            'end_time'=>'18:00:00',
            'ganre_id'=>'1',
            'level_id'=>'1',
            'province_id'=>'4',
            'price'=>'6000'
        ]);
        Test::create([
            'name'=>'eee',
            'test_date'=>Carbon::parse('2023-07-24'),
            'begin_time'=>'11:00:00',
            'end_time'=>'11:30:00',
            'ganre_id'=>'2',
            'level_id'=>'1',
            'province_id'=>'5',
            'price'=>'8000'
        ]);
        Test::create([
            'name'=>'fff',
            'test_date'=>Carbon::parse('2023-07-23'),
            'begin_time'=>'12:00:00',
            'end_time'=>'14:00:00',
            'ganre_id'=>'2',
            'level_id'=>'3',
            'province_id'=>'6',
            'price'=>'7500'
        ]);
        Test::create([
            'name'=>'ggg',
            'test_date'=>Carbon::parse('2023-07-26'),
            'begin_time'=>'09:00:00',
            'end_time'=>'09:30:00',
            'ganre_id'=>'1',
            'level_id'=>'2',
            'province_id'=>'7',
            'price'=>'3000'
        ]);
        Test::create([
            'name'=>'hhh',
            'test_date'=>Carbon::parse('2023-07-31'),
            'begin_time'=>'12:00:00',
            'end_time'=>'13:00:00',
            'ganre_id'=>'5',
            'level_id'=>'3',
            'province_id'=>'8',
            'price'=>'2500'
        ]);
        Test::create([
            'name'=>'hhh',
            'test_date'=>Carbon::parse('2023-07-30'),
            'begin_time'=>'12:00:00',
            'end_time'=>'13:00:00',
            'ganre_id'=>'5',
            'level_id'=>'3',
            'province_id'=>'9',
            'price'=>'2500'
        ]);
        Test::create([
            'name'=>'1111',
            'test_date'=>Carbon::parse('2023-07-28'),
            'begin_time'=>'12:00:00',
            'end_time'=>'13:00:00',
            'ganre_id'=>'4',
            'level_id'=>'3',
            'province_id'=>'10',
            'price'=>'2500'
        ]);
        Test::create([
            'name'=>'h2h',
            'test_date'=>Carbon::parse('2023-07-27'),
            'begin_time'=>'12:00:00',
            'end_time'=>'13:00:00',
            'ganre_id'=>'2',
            'level_id'=>'3',
            'province_id'=>'2',
            'price'=>'2500'
        ]);
        Test::create([
            'name'=>'333',
            'test_date'=>Carbon::parse('2023-07-24'),
            'begin_time'=>'04:00:00',
            'end_time'=>'07:00:00',
            'ganre_id'=>'5',
            'level_id'=>'3',
            'province_id'=>'3',
            'price'=>'2500'
        ]);
        Test::create([
            'name'=>'444',
            'test_date'=>Carbon::parse('2023-07-24'),
            'begin_time'=>'03:00:00',
            'end_time'=>'04:00:00',
            'ganre_id'=>'4',
            'level_id'=>'1',
            'province_id'=>'4',
            'price'=>'2500'
        ]);
        Test::create([
            'name'=>'555',
            'test_date'=>Carbon::parse('2023-07-24'),
            'begin_time'=>'02:00:00',
            'end_time'=>'03:00:00',
            'ganre_id'=>'3',
            'level_id'=>'3',
            'province_id'=>'5',
            'price'=>'2500'
        ]);
        Test::create([
            'name'=>'666',
            'test_date'=>Carbon::parse('2023-07-26'),
            'begin_time'=>'09:25:00',
            'end_time'=>'10:00:00',
            'ganre_id'=>'1',
            'level_id'=>'2',
            'province_id'=>'6',
            'price'=>'2500'
        ]);
        Test::create([
            'name'=>'777',
            'test_date'=>Carbon::parse('2023-07-24'),
            'begin_time'=>'12:00:00',
            'end_time'=>'13:00:00',
            'ganre_id'=>'3',
            'level_id'=>'1',
            'province_id'=>'7',
            'price'=>'2500'
        ]);
        Test::create([
            'name'=>'888',
            'test_date'=>Carbon::parse('2023-07-24'),
            'begin_time'=>'00:00:00',
            'end_time'=>'01:00:00',
            'ganre_id'=>'4',
            'level_id'=>'3',
            'province_id'=>'8',
            'price'=>'2500'
        ]);
        Test::create([
            'name'=>'nagoya',
            'test_date'=>Carbon::parse('2023-07-24'),
            'begin_time'=>'23:00:00',
            'end_time'=>'24:00:00',
            'ganre_id'=>'5',
            'level_id'=>'3',
            'province_id'=>'9',
            'price'=>'2500'
        ]);
    }
}
